# Generated by Django 4.1.7 on 2023-03-07 22:57

from django.db import migrations, models
import django.db.models.deletion
import loans.utils
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("books_copy", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Loan",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateField(auto_now_add=True)),
                (
                    "devolution_date",
                    models.DateField(default=loans.utils.default_devolution_date),
                ),
                ("is_returned", models.BooleanField(default=False)),
                (
                    "book_copy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="loans",
                        to="books_copy.bookcopy",
                    ),
                ),
            ],
        ),
    ]
